export default {
    ADD_NOTE: 'ADD_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
    SET_INPUT_CONTENT: 'SET_INPUT_CONTENT',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',

    SET_INPUT_DATE: 'SET_INPUT_DATE',
    SET_INPUT_TIME: 'SET_INPUT_TIME',
}